# config file for arrfs
# https://toml.io/en/

title = "arrfs configuration file"

# the symlink file system location
[arrfs]
# arrfs = /your/arrfs/directory
arrfs = /home/gw

[storage]
# storageN = /your/storage/path(s)
storage0 = /home/gw/projects/arrfs/arrfs/storage0
storage1 = /home/gw/projects/arrfs/arrfs/storage1

[radarr]
git_repo = "https://github.com/linuxserver/docker-radarr.git"
downloads_path = "/operations/downloads"